### ISSUE TITLE
compatibility for python 3.12 needed

### ISSUE THREAD

**Issue by realchrisward** [JimHokanson/adinstruments_sdk_python#12]
current repository seems to be compiled only up to python 3.11.
this prevents leveraging performance improvement of python 3.12 with the adi-reader library.

it looks like following the readme instructions to recompile in a python 3.12 environment is needed (to at least generate the .pyd file to permit using the library in python 3.12) - i'm not sure what is next needed to make this ready for pip?

P.S. - I really like this library - we find it very useful for loading in .adicht files for data analysis in our python scripts. I will be submitting a pull request with a pyd compiled for python 3.12.  Happy to help where I am able to support this project.

**Comment by realchrisward** [comment]
pull request #13 is associated with this issue

**Comment by JimHokanson** [comment]
Fixed in latest update along with 3.13 (for 64 bit Windows)
